# Generated by Django 2.1.4 on 2018-12-12 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentImportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='studentimport',
            name='students',
            field=models.ManyToManyField(related_name='users', to='courses.StudentImportUser'),
        ),
    ]
