# Generated by Django 2.1.5 on 2019-02-16 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181211_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimport',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course', unique=True),
        ),
        migrations.AlterField(
            model_name='studentimportuser',
            name='user',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
