# Generated by Django 2.1.5 on 2019-02-17 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190215_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimport',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
