# Generated by Django 3.1 on 2021-10-02 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_set', to='courses.course'),
        ),
    ]
