# Generated by Django 3.1 on 2021-10-08 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20211002_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
