# Generated by Django 3.1 on 2021-10-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_period_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sort_assignments_by',
            field=models.CharField(choices=[('due_date', 'Due Date'), ('name', 'Name')], default='due_date', max_length=30),
        ),
    ]
