# Generated by Django 3.2.14 on 2022-08-03 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_auto_20220802_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taught_periods', to=settings.AUTH_USER_MODEL),
        ),
    ]
