# Generated by Django 3.2.19 on 2023-07-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_period_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentimport',
            options={'verbose_name': 'Student Import'},
        ),
        migrations.AlterModelOptions(
            name='studentimportuser',
            options={'verbose_name': 'Imported Student'},
        ),
    ]
