# Generated by Django 4.2.13 on 2024-06-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20230709_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='permission',
            field=models.CharField(choices=[('w', 'view and submit assignments'), ('r', 'view assignments'), ('-', 'see nothing')], default='r', max_length=1),
        ),
    ]
