# Generated by Django 4.2.13 on 2024-06-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('courses', '0014_course_archived'), ('courses', '0015_course_permission'), ('courses', '0016_alter_course_permission')]

    dependencies = [
        ('courses', '0013_auto_20230709_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='permission',
            field=models.CharField(choices=[('rw', 'view and submit assignments'), ('r', 'view assignments'), ('-', 'see nothing')], default='r', max_length=30),
        ),
    ]
