default_stages: [commit, push]
fail_fast: false
exclude: ^tin/(static/.*vendor|.*migrations)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
        name: validate python
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-toml
      - id: detect-private-key
      - id: check-yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        files: ^.*\.(py|md|rst)$
        # TODO: Remove after python version >= 3.11
        additional_dependencies:
          - tomli
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ "--fix", "--exit-non-zero-on-fix" ]
        files: ^tin/.*
        name: ruff lint
      - id: ruff-format
        files: ^tin/.*
