default_stages: [pre-commit, pre-push]
fail_fast: false
exclude: ^tin/(static/.*vendor|.*migrations)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
        name: validate python
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-toml
      - id: detect-private-key
      - id: check-yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        files: ^.*\.(py|md|rst)$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [ "--fix", "--exit-non-zero-on-fix" ]
        files: ^tin/.*
        name: ruff lint
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [ javascript, css ]
