# Generated by Django 2.1.4 on 2018-12-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_has_been_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='filename',
            field=models.FilePathField(null=True, recursive=True, verbose_name='/home/theo/csl/tin/tin/media'),
        ),
    ]
