# Generated by Django 2.1.4 on 2018-12-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20181209_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grader_output',
            field=models.CharField(default='', max_length=10240),
            preserve_default=False,
        ),
    ]
