# Generated by Django 2.1.5 on 2019-02-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submission_grader_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grader_errors',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
