# Generated by Django 2.1.5 on 2019-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_submission_grader_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
