# Generated by Django 2.2.3 on 2019-07-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_auto_20190725_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='points_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
