# Generated by Django 2.2.5 on 2019-09-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_auto_20190730_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grader_pid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
