# Generated by Django 2.2.5 on 2019-09-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_auto_20190911_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grader_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
