# Generated by Django 2.2.5 on 2019-09-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_submission_grader_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='kill_requested',
            field=models.BooleanField(default=False),
        ),
    ]
