# Generated by Django 2.2.5 on 2019-09-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_submission_grader_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grader_start_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
