# Generated by Django 2.2.5 on 2019-09-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_submission_kill_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grader_errors',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
