# Generated by Django 3.2.14 on 2022-08-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_auto_20190928_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
