# Generated by Django 3.2.19 on 2023-09-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_auto_20230715_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
