# Generated by Django 3.2.21 on 2023-11-08 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0025_assignment_last_action_output'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0021_alter_submission_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_submissions', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_submissions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_submission', to='submissions.submission')),
            ],
        ),
    ]
