# Generated by Django 3.2.21 on 2023-11-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0022_publishedsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishedsubmission',
            options={'get_latest_by': 'submission__date_submitted'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'get_latest_by': 'date_submitted'},
        ),
    ]
