# Generated by Django 2.2.5 on 2019-10-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0011_assignment_grader_has_network_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Virtualenv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fully_created', models.BooleanField()),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venv', to='assignments.Assignment')),
            ],
        ),
    ]
