# Generated by Django 2.2.6 on 2019-10-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualenv',
            name='installing_packages',
            field=models.BooleanField(default=False),
        ),
    ]
