# Generated by Django 2.2.6 on 2019-10-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venvs', '0002_virtualenv_installing_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualenv',
            name='package_installation_output',
            field=models.CharField(blank=True, default='', max_length=16384),
        ),
    ]
