# Generated by Django 3.2.25 on 2024-03-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venvs', '0004_alter_virtualenv_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fully_created', models.BooleanField()),
                ('installing_packages', models.BooleanField(default=False)),
                ('package_installation_output', models.CharField(blank=True, default='', max_length=16384)),
            ],
        ),
        migrations.DeleteModel(
            name='Virtualenv',
        ),
    ]
