# Generated by Django 4.2.16 on 2024-11-11 02:11

from django.db import migrations, models
import django.db.models.deletion


def venv_default_to_python310(apps, schema_editor):
    """Defaults venvs created previously to use Python 3.10 at /usr/bin/python3.10."""

    Language = apps.get_model("assignments", "Language")
    db_alias = schema_editor.connection.alias
    python_310, created = Language.objects.using(db_alias).get_or_create(
        name="Python 3.10",
        info={"python3": "/usr/bin/python3.10", "version": 3.10},
        language="P",
    )

    Venv = apps.get_model("venvs", "Venv")
    Venv.objects.using(db_alias).filter(language__isnull=True).update(language=python_310)

    # avoid creating a useless row
    if created and not python_310.venv_set.exists():
        python_310.delete()


def delete_python_310_from_venvs(apps, schema_editor):
    Language = apps.get_model("assignments", "Language")
    db_alias = schema_editor.connection.alias
    python_310 = (
        Language.objects.using(db_alias)
        .filter(
            name="Python 3.10",
            info={"python3": "/usr/bin/python3.10", "version": 3.10},
            language="P",
            is_deprecated=False,
        )
        .first()
    )

    if python_310 is not None:
        Venv = apps.get_model("venvs", "Venv")
        Venv.objects.filter(language=python_310).update(language=None)


# fmt: off
class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0034_language"),
        ("venvs", "0005_auto_20240328_0033"),
    ]

    operations = [
        migrations.AddField(
            model_name="venv",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venv_set",
                to="assignments.language",
            ),
        ),
        migrations.RunPython(venv_default_to_python310, delete_python_310_from_venvs),
        migrations.AlterField(
            model_name="venv",
            name="language",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venv_set",
                to="assignments.language",
            ),
        ),
    ]
