# Generated by Django 2.2.3 on 2019-07-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerpackage',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='packages', to='assignments.Assignment'),
        ),
    ]
