# Generated by Django 4.2.15 on 2024-09-04 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_sysadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
