# Generated by Django 2.1.4 on 2018-12-05 02:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('points_possible', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('assigned', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.Course')),
            ],
        ),
    ]
