# Generated by Django 2.1.5 on 2019-02-16 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20190215_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grader_timeout',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
