# Generated by Django 2.1.7 on 2019-02-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20190215_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='has_network_access',
            field=models.BooleanField(default=False),
        ),
    ]
