# Generated by Django 2.2.3 on 2019-07-30 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_requested_num_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='points_possible',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
