# Generated by Django 2.2.3 on 2019-08-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20190730_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='has_network_access',
        ),
    ]
