# Generated by Django 2.2.4 on 2019-08-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_remove_assignment_has_network_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='has_network_access',
            field=models.BooleanField(default=False),
        ),
    ]
