# Generated by Django 2.2.4 on 2019-08-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_assignment_has_network_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='requested_num_containers',
        ),
    ]
