# Generated by Django 2.2.5 on 2019-09-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_remove_assignment_requested_num_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(max_length=4096),
        ),
    ]
