# Generated by Django 2.2.6 on 2019-10-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_assignment_grader_has_network_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='enable_grader_timeout',
            field=models.BooleanField(default=True),
        ),
    ]
