# Generated by Django 3.1 on 2021-10-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_auto_20200526_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
