# Generated by Django 3.1 on 2022-04-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_sort_assignments_by'),
        ('assignments', '0015_assignment_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='folder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.folder'),
        ),
    ]
