# Generated by Django 3.1 on 2022-04-16 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_auto_20220414_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.folder'),
        ),
    ]
