# Generated by Django 3.2.14 on 2022-08-14 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0019_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='action',
            field=models.CharField(choices=[('0', 'Log only'), ('1', 'Color Change'), ('2', 'Lock')], default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('severity', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_messages', to='assignments.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
