# Generated by Django 3.2.14 on 2022-08-14 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_auto_20220814_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
