# Generated by Django 3.2.17 on 2023-03-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0021_logmessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='language',
            field=models.CharField(choices=[('P', 'Python 3'), ('J', 'Java')], default='P', max_length=1),
        ),
    ]
