# Generated by Django 3.2.19 on 2023-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0022_assignment_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='filename',
            field=models.CharField(default='main.py', max_length=50),
        ),
    ]
