# Generated by Django 3.2.19 on 2023-10-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0024_auto_20230709_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='last_action_output',
            field=models.CharField(blank=True, default='', max_length=16384),
        ),
    ]
