# Generated by Django 3.2.25 on 2024-03-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venvs', '0005_auto_20240328_0033'),
        ('assignments', '0027_mossresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='venv',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='venvs.venv'),
        ),
    ]
