# Generated by Django 4.2.11 on 2024-05-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0028_assignment_venv"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="markdown",
            field=models.BooleanField(default=False),
        ),
    ]
