# Generated by Django 4.2.11 on 2024-05-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0029_assignment_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="autocomplete",
            field=models.BooleanField(default=False),
        ),
    ]
