# Generated by Django 4.2.13 on 2024-05-27 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assignments", "0029_assignment_markdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizLogMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField(max_length=100)),
                ("severity", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_quiz",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignment",
            name="quiz_action",
            field=models.CharField(
                choices=[("0", "Log only"), ("1", "Color Change"), ("2", "Lock")],
                default="2",
                max_length=1,
            ),
        ),
        migrations.DeleteModel(
            name="LogMessage",
        ),
        migrations.AddField(
            model_name="quizlogmessage",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_messages",
                to="assignments.assignment",
            ),
        ),
        migrations.AddField(
            model_name="quizlogmessage",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
