# Generated by Django 4.2.15 on 2024-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0032_assignment_quiz_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaction',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
