# Generated by Django 4.2.15 on 2025-02-21 01:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0032_assignment_quiz_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_cap', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('submission_cap_after_due', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_caps', to='assignments.assignment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='submissioncap',
            constraint=models.UniqueConstraint(fields=('student', 'assignment'), name='unique_type'),
        ),
        migrations.AddConstraint(
            model_name='submissioncap',
            constraint=models.CheckConstraint(condition=models.Q(('submission_cap__isnull', False), ('submission_cap_after_due__isnull', False), _connector='OR'), name='has_submission_cap', violation_error_message='Either the submission cap before or after the due date has to be set'),
        ),
    ]
