# Generated by Django 4.2.16 on 2024-11-11 01:40

from django.db import migrations, models


def migrate_to_foreignkey(apps, schema_editor):
    """Creates a default :class:`.Language` model for each assignment.

    This converts the old language field to a foreign key to the new language model.
    """

    Language = apps.get_model("assignments", "Language")
    db_alias = schema_editor.connection.alias
    python_310, py_created = Language.objects.using(db_alias).get_or_create(
        name="Python 3.10",
        info={"python3": "/usr/bin/python3.10", "version": 3.10},
        language="P",
    )

    Assignment = apps.get_model("assignments", "Assignment")
    Assignment.objects.using(db_alias).update(language_details=python_310)

    # avoid creating empty models
    if py_created and not python_310.assignment_set.exists():
        python_310.delete()


def revert_default_language(apps, schema_editor):
    """Converts the foreign key :class:`.Language` back to the old ``language`` field."""

    Assignment = apps.get_model("assignments", "Assignment")
    db_alias = schema_editor.connection.alias
    Assignment.objects.using(db_alias).update(language="P")


# fmt: off
class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0033_submissioncap_submissioncap_unique_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deprecated', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('P', 'Python 3'), ('J', 'Java')], max_length=1)),
                ('name', models.CharField(help_text='The name of the language', max_length=50)),
                ('info', models.JSONField()),
            ],
            options={'ordering': ['-language', "-info__version"]},

        ),
        migrations.AddField(
            model_name="assignment",
            name="language_details",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="assignment_set",
                to="assignments.language",
            ),
        ),
        migrations.RunPython(migrate_to_foreignkey, revert_default_language),
        migrations.AlterField(
            model_name="assignment",
            name="language_details",
            field=models.ForeignKey(
                null=False,
                on_delete=models.deletion.CASCADE,
                related_name="assignment_set",
                to="assignments.language",
            ),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='language',
        ),
    ]
