# Generated by Django 5.2.10 on 2026-01-27 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0034_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submissioncap',
            name='unique_type',
        ),
        migrations.AddConstraint(
            model_name='submissioncap',
            constraint=models.UniqueConstraint(fields=('student', 'assignment'), name='unique_type', nulls_distinct=False),
        ),
    ]
