# Generated by Django 5.2.12 on 2026-03-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0035_remove_submissioncap_unique_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaction',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
